FROM golang as builder
WORKDIR /go/src/app

# caching rathole
COPY scripts scripts
RUN ./scripts/download-rathole.sh

COPY src/client/. .
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -o /go/bin/client

FROM gcr.io/distroless/cc-debian12 as release

COPY --from=builder /go/bin/client /usr/bin/client

ENTRYPOINT ["client"]